version: '3.7'

services:
  setting_up_ghost_in_azure:
    image: geircode/setting_up_ghost_in_azure:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # This will overwrite the default build arguments in the Dockerfile with the value of the enviroment variable value
        # The value "DOCKER_LATEST_VERSION_FILE" comes from either .env or from the shell running the docker-compose command
        docker_latest_version_file_arg: ${DOCKER_LATEST_VERSION_FILE} 
    container_name: setting_up_ghost_in_azure-1
    volumes:
      - ".:/app"       
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - setting_up_ghost_in_azure_network
networks:
  setting_up_ghost_in_azure_network:
    name: setting_up_ghost_in_azure_network
    external: true