version: '3.5'

services:
  setting_up_ghost_in_azure:
    image: geircode/setting_up_ghost_in_azure:latest
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: setting_up_ghost_in_azure-1
    volumes:
      - ".:/app"       
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - setting_up_ghost_in_azure_network
networks:
  setting_up_ghost_in_azure_network:
          docker-compose.yml