version: '3.7'

services:
  setting_up_ghost_in_azure-filecontainer:
    image: geircode/setting_up_ghost_in_azure-filecontainer:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setting_up_ghost_in_azure-filecontainer-1
    networks:
      - setting_up_ghost_in_azure-filecontainer-network      

networks:
  setting_up_ghost_in_azure-filecontainer-network:
    name: setting_up_ghost_in_azure-filecontainer-network    
    