version: '3.5'

services:
  templateworkspace-filecontainer:
    image: geircode/templateworkspace-filecontainer:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: templateworkspace-filecontainer-1
    networks:
      - templateworkspace-filecontainer-network      

networks:
  templateworkspace-filecontainer-network:
    name: templateworkspace-filecontainer-network    
    