version: '3.5'

services:
  setting_up_ghost_in_azure_secrets:
    image: geircode/setting_up_ghost_in_azure_secrets:latest
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: dockersecrets__setting_up_ghost_in_azure-1
    volumes:
      - "../../DockerSecrets/setting_up_ghost_in_azure_secrets:/setting_up_ghost_in_azure_secrets"
    working_dir: /setting_up_ghost_in_azure_secrets
    networks:
      - setting_up_ghost_in_azure_secrets-network    
networks:
  setting_up_ghost_in_azure_secrets-network:

